/**
 * publicController.js
 *
 * Handles all public endpoints (no authentication required).
 * These are called when a customer scans a merchant QR Code without the Retanza app.
 *
 * Endpoints:
 *   GET  /api/public/merchant/:code          → Public merchant profile
 *   POST /api/public/merchant/:code/scan     → Record QR scan for statistics
 *   POST /api/public/loyalty-card/create     → Create a Guest Loyalty Card
 *   POST /api/public/loyalty-card/wallet-pass → Generate a Wallet pass on demand (Lazy)
 */

const Commerce = require('../models/Commerce');
const QRCode = require('../models/QRCode');
const GuestLoyaltyCard = require('../models/GuestLoyaltyCard');
const walletService = require('../services/walletService');
const { reconcileGuestCards } = require('../services/reconciliationService');

/**
 * Finds a Commerce by QR code.
 * Strategy:
 *   1. Try Commerce.merchantCode (new format, M###### or RC-XXXX)
 *   2. Fall back to QRCode collection (stores the RC-XXXXXXXX code separately)
 * This handles both old and new merchants transparently.
 */
const findCommerceByCode = async (code) => {
  const upperCode = code.toUpperCase();

  // Strategy 1: direct merchantCode match
  let commerce = await Commerce.findOne({ merchantCode: upperCode }).select(
    'name category description logo coverImage brandColor contact loyaltyProgram status merchantCode'
  );
  if (commerce) return commerce;

  // Strategy 2: look up in QRCode collection (code generated by generateQRCode endpoint)
  const qrDoc = await QRCode.findOne({ code: upperCode }).select('commerce');
  if (!qrDoc) return null;

  commerce = await Commerce.findById(qrDoc.commerce).select(
    'name category description logo coverImage brandColor contact loyaltyProgram status merchantCode'
  );
  return commerce;
};


// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Generates a unique, collision-resistant public card ID.
 * Format: RTC-XXXX-XXXX (alphanumeric, no ambiguous chars like O/0 I/1)
 */
const generateCardPublicId = () => {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const segment = () =>
    Array.from({ length: 4 }, () => chars[Math.floor(Math.random() * chars.length)]).join('');
  return `RTC-${segment()}-${segment()}`;
};

/**
 * Maps a Commerce document to the public profile shape expected by the frontend.
 * Never exposes internal IDs, merchant contacts, or sensitive data.
 */
const toPublicProfile = (commerce) => ({
  name: commerce.name,
  category: commerce.category,
  description: commerce.description || '',
  logoUrl: commerce.logo || null,
  bannerUrl: commerce.coverImage || null,
  primaryColor: commerce.brandColor || '#D73E26',
  secondaryColor: '#FFFFFF',
  address: commerce.contact?.address
    ? `${commerce.contact.address}${commerce.contact.city ? ', ' + commerce.contact.city : ''}`
    : null,
  loyaltyProgram: {
    type: commerce.loyaltyProgram?.type || 'points',
    totalStamps: commerce.loyaltyProgram?.stampsRequired,
    currentStamps: 0,
    reward: commerce.loyaltyProgram?.rewardDescription,
    pointsPerEuro: commerce.loyaltyProgram?.pointsPerEuro,
    cashbackRate: commerce.loyaltyProgram?.cashbackPercentage,
  },
  isActive: commerce.status === 'active',
});

// ── In-memory scan deduplication (production: use Redis) ─────────────────────
// Key: `${ip}:${code}` | Value: timestamp of last recorded scan
const scanDedup = new Map();
const SCAN_DEDUP_TTL_MS = 60 * 60 * 1000; // 1 hour

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/public/merchant/:code
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Returns the public profile of a merchant by their QR merchantCode.
 * Also increments QR scan count for basic statistics.
 */
const getPublicMerchant = async (req, res) => {
  try {
    const { code } = req.params;

    // Validate format
    if (!code || !/^[A-Z0-9-]{3,20}$/i.test(code)) {
      return res.status(400).json({ success: false, message: 'Code commerçant invalide.' });
    }

    const commerce = await findCommerceByCode(code);

    if (!commerce) {
      return res.status(404).json({ success: false, message: 'Commerce introuvable.' });
    }

    if (commerce.status !== 'active') {
      return res.status(403).json({
        success: false,
        message: 'Ce commerce ne fait plus partie du réseau Retenza.',
      });
    }

    return res.json({
      success: true,
      data: toPublicProfile(commerce),
    });
  } catch (err) {
    console.error('[PublicController] getPublicMerchant error:', err.message);
    return res.status(500).json({ success: false, message: 'Erreur serveur.' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/public/merchant/:code/scan
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Records a QR scan for merchant statistics.
 * Deduplicates scans per IP to avoid stat farming.
 */
const recordScan = async (req, res) => {
  try {
    const { code } = req.params;
    const ip = req.ip || req.connection?.remoteAddress || 'unknown';
    const { userAgent = '', source = 'qr_camera' } = req.body;

    const dedupKey = `${ip}:${code.toUpperCase()}`;
    const lastScan = scanDedup.get(dedupKey);
    const now = Date.now();

    if (lastScan && now - lastScan < SCAN_DEDUP_TTL_MS) {
      // Already counted this scan recently — acknowledge without recording
      return res.json({ success: true, message: 'Scan already recorded recently.', deduplicated: true });
    }

    // Mark dedup
    scanDedup.set(dedupKey, now);

    // Clean old entries periodically (every 500 scans)
    if (scanDedup.size > 500) {
      for (const [k, t] of scanDedup.entries()) {
        if (now - t > SCAN_DEDUP_TTL_MS) scanDedup.delete(k);
      }
    }

    // Find the commerce and increment scan count (best-effort, no throw on failure)
    try {
      const scanCommerce = await findCommerceByCode(code);
      if (scanCommerce) {
        await Commerce.findByIdAndUpdate(
          scanCommerce._id,
          { $inc: { 'scanStats.totalScans': 1 }, $set: { 'scanStats.lastScannedAt': new Date() } }
        );
      }
    } catch {
      // Scan tracking is non-critical — don't fail the request
    }

    console.log(`[PublicController] QR_SCANNED: code=${code}, source=${source}, ip=${ip.slice(0, 8)}...`);

    return res.json({ success: true, message: 'Scan enregistré.' });
  } catch (err) {
    console.error('[PublicController] recordScan error:', err.message);
    return res.status(500).json({ success: false, message: 'Erreur serveur.' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/public/loyalty-card/create
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Creates a Guest Loyalty Card for a visitor.
 *
 * Logic:
 * 1. Validate all fields
 * 2. Find the commerce by merchantCode
 * 3. Check for existing card (same email OR phone, same merchant) → return existing
 * 4. Generate cardPublicId
 * 5. Create GuestLoyaltyCard in DB
 * 6. Return cardPublicId (no Wallet pass generated here — Lazy approach)
 */
const createGuestCard = async (req, res) => {
  try {
    const { merchantCode, firstName, lastName, email, phone } = req.body;

    // ── 1. Validation ────────────────────────────────────────────────────────
    const missing = ['merchantCode', 'firstName', 'lastName', 'email', 'phone'].filter(
      (f) => !req.body[f]?.trim()
    );
    if (missing.length > 0) {
      return res.status(400).json({
        success: false,
        message: `Champs manquants : ${missing.join(', ')}`,
      });
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return res.status(400).json({ success: false, message: "Format d'email invalide." });
    }

    const phoneRegex = /^\+?[\d\s\-().]{7,20}$/;
    if (!phoneRegex.test(phone)) {
      return res.status(400).json({ success: false, message: 'Format de numéro de téléphone invalide.' });
    }

    // ── 2. Find active commerce ──────────────────────────────────────────────
    const commerce = await findCommerceByCode(merchantCode);

    if (!commerce || commerce.status !== 'active') {
      return res.status(404).json({ success: false, message: 'Commerce partenaire introuvable ou inactif.' });
    }

    const normalizedEmail = email.trim().toLowerCase();
    const normalizedPhone = phone.trim();

    // ── 3. Check for existing card (anti-duplicate) ──────────────────────────
    const existingCard = await GuestLoyaltyCard.findOne({
      merchantId: commerce._id,
      $or: [{ email: normalizedEmail }, { phone: normalizedPhone }],
      status: { $ne: 'suspended' },
    });

    if (existingCard) {
      console.log(`[PublicController] Existing card found: ${existingCard.cardPublicId}`);
      return res.json({
        success: true,
        data: {
          cardPublicId: existingCard.cardPublicId,
          isNewCard: false,
          message: `Vous possédez déjà une carte pour ${commerce.name}. Votre carte existante vous a été retournée.`,
        },
      });
    }

    // ── 4. Generate collision-resistant cardPublicId ──────────────────────────
    let cardPublicId;
    let attempts = 0;
    do {
      cardPublicId = generateCardPublicId();
      const collision = await GuestLoyaltyCard.findOne({ cardPublicId });
      if (!collision) break;
      attempts++;
    } while (attempts < 5);

    if (attempts >= 5) {
      return res.status(500).json({ success: false, message: 'Erreur de génération d\'identifiant. Veuillez réessayer.' });
    }

    // ── 5. Create GuestLoyaltyCard ────────────────────────────────────────────
    const card = await GuestLoyaltyCard.create({
      cardPublicId,
      firstName: firstName.trim(),
      lastName: lastName.trim(),
      email: normalizedEmail,
      phone: normalizedPhone,
      merchantId: commerce._id,
      merchantPublicCode: merchantCode.toUpperCase(),
      status: 'active',
      points: 0,
      stamps: 0,
      cashback: 0,
    });

    console.log(`[PublicController] GUEST_CARD_CREATED: ${card.cardPublicId} for commerce ${commerce.name}`);

    // ── 6. Return card info (no Wallet pass here — Lazy approach) ─────────────
    return res.status(201).json({
      success: true,
      data: {
        cardPublicId: card.cardPublicId,
        isNewCard: true,
        message: `Votre carte de fidélité ${commerce.name} a été créée avec succès !`,
      },
    });
  } catch (err) {
    console.error('[PublicController] createGuestCard error:', err.message);
    return res.status(500).json({ success: false, message: 'Erreur lors de la création de la carte.' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/public/loyalty-card/wallet-pass
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generates a Wallet pass ON DEMAND (Lazy Pass Generation).
 * Called only when the user clicks "Add to Google Wallet" or "Add to Apple Wallet".
 *
 * This avoids creating unused passes and reduces API calls to Wallet providers.
 */
const generateWalletPassForGuest = async (req, res) => {
  try {
    const { cardPublicId, provider } = req.body;

    if (!cardPublicId || !provider) {
      return res.status(400).json({ success: false, message: 'cardPublicId et provider sont requis.' });
    }

    if (!['google', 'apple'].includes(provider)) {
      return res.status(400).json({ success: false, message: 'Provider invalide. Valeurs acceptées : google, apple.' });
    }

    // Find the card
    const card = await GuestLoyaltyCard.findOne({ cardPublicId, status: 'active' });
    if (!card) {
      return res.status(404).json({ success: false, message: 'Carte introuvable ou suspendue.' });
    }

    // Find the commerce
    const commerce = await Commerce.findById(card.merchantId);
    if (!commerce || commerce.status !== 'active') {
      return res.status(404).json({ success: false, message: 'Commerce associé introuvable.' });
    }

    // Check if a pass already exists for this provider
    const existingPass = card.walletPasses.find((p) => p.provider === provider);

    if (provider === 'google') {
      // ── Google Wallet ──────────────────────────────────────────────────────
      // Build a synthetic client and loyaltyAccount object compatible with walletService
      const syntheticClient = {
        _id: card._id,
        firstName: card.firstName,
        lastName: card.lastName,
      };

      const syntheticLoyaltyAccount = {
        _id: card._id,
        // cardPublicId → used by walletService as the QR barcode value on the Wallet card.
        // The Flutter app scans this QR to import the card automatically.
        cardPublicId: card.cardPublicId,
        points: card.points,
        stamps: card.stamps,
        cashbackBalance: card.cashback,
        createdAt: card.createdAt,
      };

      const result = await walletService.generateWalletPass(
        syntheticClient,
        commerce,
        syntheticLoyaltyAccount,
        'google'
      );

      // Persist the wallet pass ref if not already stored
      if (!existingPass) {
        card.walletPasses.push({ provider: 'google', objectId: result.objectId });
        await card.save();
      }

      console.log(`[PublicController] WALLET_PASS_GENERATED: google for card ${cardPublicId}`);

      return res.json({
        success: true,
        data: {
          provider: 'google',
          addUrl: result.passUrl,
        },
      });
    }

    if (provider === 'apple') {
      // ── Apple Wallet ───────────────────────────────────────────────────────
      // Apple PassKit integration — placeholder until certificates are configured
      // Structure follows the WalletProvider pattern for easy activation in Phase 3
      const appleObjectId = `apple_guest_${cardPublicId}`;

      if (!existingPass) {
        card.walletPasses.push({ provider: 'apple', objectId: appleObjectId });
        await card.save();
      }

      // TODO Phase 2 Apple: Replace with real PassKit generation
      // const pkpassBuffer = await appleWalletService.generatePass(card, commerce);
      // return res.set('Content-Type', 'application/vnd.apple.pkpass').send(pkpassBuffer);
      const applePassUrl = `${process.env.APP_BASE_URL}/api/public/loyalty-card/${cardPublicId}/apple.pkpass`;

      console.log(`[PublicController] WALLET_PASS_GENERATED: apple for card ${cardPublicId}`);

      return res.json({
        success: true,
        data: {
          provider: 'apple',
          addUrl: applePassUrl,
        },
      });
    }
  } catch (err) {
    console.error('[PublicController] generateWalletPassForGuest error:', err.message);
    return res.status(500).json({ success: false, message: 'Erreur lors de la génération du pass Wallet.' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/public/loyalty-card/reconcile  (Protected — requires JWT)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Manually triggers reconciliation for the authenticated user.
 * Useful if the user registered before they had guest cards,
 * or if they add a new phone number later.
 *
 * Protected endpoint — requires valid JWT (req.user populated by auth middleware).
 */
const manualReconcile = async (req, res) => {
  try {
    const { email, phone } = req.user;

    if (!email && !phone) {
      return res.status(400).json({
        success: false,
        message: 'Aucun email ou téléphone associé à votre compte.',
      });
    }

    const result = await reconcileGuestCards({
      retenzaUserId: req.user._id,
      email: email?.toLowerCase().trim() || '',
      phone: phone?.trim() || '',
    });

    console.log(
      `[PublicController] MANUAL_RECONCILE: userId=${req.user._id} merged=${result.mergedCount}`
    );

    return res.json({
      success: true,
      data: {
        mergedCount: result.mergedCount,
        mergedCards: result.mergedCards,
        message:
          result.mergedCount === 0
            ? 'Aucune carte à importer pour votre compte.'
            : `${result.mergedCount} carte(s) de fidélité importée(s) dans votre compte Retenza !`,
        errors: result.errors.length > 0 ? result.errors : undefined,
      },
    });
  } catch (err) {
    console.error('[PublicController] manualReconcile error:', err.message);
    return res.status(500).json({ success: false, message: 'Erreur lors de la réconciliation.' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// GET /api/public/loyalty-card/lookup/:cardPublicId
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Looks up a GuestLoyaltyCard by its cardPublicId.
 *
 * Used by the Retenza Flutter app when scanning the QR on a Wallet pass.
 * Returns only the minimum info needed to confirm the card and trigger
 * reconciliation — no sensitive data (email/phone) is exposed.
 *
 * Flow:
 *   App scans QR → reads "RTC-XXXX-XXXX" → calls this endpoint
 *   → displays "Found card for Café ABC" → user confirms → reconcile()
 */
const lookupCardByPublicId = async (req, res) => {
  try {
    const { cardPublicId } = req.params;

    if (!cardPublicId || !/^RTC-[A-Z0-9]{4}-[A-Z0-9]{4}$/i.test(cardPublicId)) {
      return res.status(400).json({ success: false, message: 'Format de cardPublicId invalide.' });
    }

    const card = await GuestLoyaltyCard.findOne({
      cardPublicId: cardPublicId.toUpperCase(),
    }).select('cardPublicId merchantPublicCode merchantId status firstName createdAt');

    if (!card) {
      return res.status(404).json({ success: false, message: 'Carte introuvable.' });
    }

    // Get commerce name for display
    const commerce = await Commerce.findById(card.merchantId).select('name category brandColor logo');

    return res.json({
      success: true,
      data: {
        cardPublicId: card.cardPublicId,
        status: card.status,
        createdAt: card.createdAt,
        // First name only — enough to confirm "Yes, this is my card" without exposing full identity
        firstName: card.firstName,
        merchant: commerce
          ? {
              name: commerce.name,
              category: commerce.category,
              brandColor: commerce.brandColor,
              logoUrl: commerce.logo,
              publicCode: card.merchantPublicCode,
            }
          : { name: 'Commerce inconnu', publicCode: card.merchantPublicCode },
      },
    });
  } catch (err) {
    console.error('[PublicController] lookupCardByPublicId error:', err.message);
    return res.status(500).json({ success: false, message: 'Erreur serveur.' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────

module.exports = {
  getPublicMerchant,
  recordScan,
  createGuestCard,
  generateWalletPassForGuest,
  manualReconcile,
  lookupCardByPublicId,
};

