'use strict';
const connectDB=require('../config/db'); const {audit}=require('../utils/audit');
const overview=async(req,res)=>{const db=await connectDB(); const [total,active,suspended,health,last]=await Promise.all([db.collection('commerces').countDocuments(),db.collection('commerces').countDocuments({status:'active'}),db.collection('commerces').countDocuments({status:'suspended'}),db.collection('system_health').find().toArray(),db.collection('job_runs').find().sort({started_at:-1}).limit(10).toArray()]); await audit(req,'super_admin.overview');res.json({commerces:{total,active,suspended},health,last_jobs:last});};
const list=async(req,res)=>{const db=await connectDB();const q=String(req.query.q||'');const status=req.query.status;const match={...(status?{status}:{}),...(q?{name:{$regex:q,$options:'i'}}:{})};const rows=await db.collection('commerces').aggregate([{$match:match},{$lookup:{from:'clients',localField:'commerce_id',foreignField:'commerce_id',as:'clients'}},{$project:{commerce_id:1,brand_id:1,name:1,status:1,updated_at:1,suspended_at:1,client_count:{$size:'$clients'}}}]).toArray();await audit(req,'super_admin.commerces.list');res.json(rows);};
const detail=async(req,res)=>{const db=await connectDB(),id=req.params.commerceId;const [commerce,settings,campaigns,jobs]=await Promise.all([db.collection('commerces').findOne({commerce_id:id}),db.collection('commerces_settings').findOne({brand_id:id.replace(/_\d+$/,'')}),db.collection('campagnes_envoyees').find({commerce_id:id}).sort({sent_at:-1}).limit(10).toArray(),db.collection('job_runs').find({commerce_id:id}).sort({started_at:-1}).limit(20).toArray()]);if(!commerce)return res.status(404).json({error:'Commerce introuvable.'});await audit(req,'super_admin.commerce.view',{type:'commerce',id,commerce_id:id});res.json({commerce,settings,campaigns,jobs});};
const status=async(req,res)=>{const {status:next,reason=''}=req.body||{};if(!['active','suspended'].includes(next)||(next==='suspended'&&!reason.trim()))return res.status(400).json({error:'Statut et motif de suspension requis.'});const db=await connectDB(),id=req.params.commerceId;const update=next==='suspended'?{$set:{status:next,suspended_at:new Date(),suspended_by:req.auth.userId,suspension_reason:reason,updated_at:new Date()}}:{$set:{status:next,updated_at:new Date()},$unset:{suspended_at:'',suspended_by:'',suspension_reason:''}};const r=await db.collection('commerces').findOneAndUpdate({commerce_id:id},update,{returnDocument:'after'});if(!r.value)return res.status(404).json({error:'Commerce introuvable.'});await audit(req,`commerce.${next}`,{type:'commerce',id,commerce_id:id},{reason});res.json(r.value);};
const health=async(req,res)=>{const db=await connectDB();res.json({health:await db.collection('system_health').find().toArray(),jobs:await db.collection('job_runs').find().sort({started_at:-1}).limit(100).toArray()});};
const logs=async(req,res)=>{const db=await connectDB();res.json(await db.collection('audit_logs').find().sort({occurred_at:-1}).limit(100).toArray());};
module.exports={overview,list,detail,status,health,logs};
